### ISSUE TITLE
Choose Business Questions

### ISSUE THREAD

**Issue by leaflettuce** [leaflettuce/teradata_challenge#2]
Determine focus for the project and analysis.

RESOURCE: _business_questions.txt_ in main dir.

**Comment by mitchb63** [comment]
It appears the team #2 is going to start by looking at the following:

Serving Spouses Program (5)
 
Q: What is the average amount in days that a military spouse spends in the HHUSA program? 
 
    How does this differ from the average veteran client? 
    What is the demographic profile of the military spouses who are registering (gender, location, service members status, level of education?)  
    How does their Service Members status affect their time to hired status? (Note Service Members status is a new field we have just started tracking.)
 
 Q: Is there a correlation between education level and the black rate for military spouses. 
 
    What percentage of military spouse clients say that they are underemployed vs. unemployed? 
    How many spouses who registered for our services who say that they are underemployed turn blue vs grey? (Would like to see this data because military spouses tend to remain underemployed.)

**Comment by leaflettuce** [comment]
Awesome, Looks like our team will be focusing on the following:

Q: Is there anything in the client's demographic profile that indicates that a client is more likely to become a confirmed hire or any other outcome?
```
Context: All of our contact records have Created Dates signifying when they first entered into the
             Hire Heroes USA system, but all clients have a Client Type and Client Category. These 
              individuals are also identified with the Client field. Client Types of Online Registrant, 
              Onward to Opportunity, and AVR are considered part of our PaCT program. 

             Nearly all of these clients registered through one of our registration portals. AVRs 
             (Attempted Veteran Registrants) were not selected for assignment and were sent
              messaging encouraging them to register again. If selected, they then become Online 
              Registrants. Thus, Client Type just denotes a current status. Current (and former) AVRs
              are identified by the AVR field.
```
Q: What can we prove - quantitatively - that our volunteers are increasing the overall effectiveness of our program?  
```
Does working with a volunteer raise the probability of a client getting hired or getting hire sooner? 
Are there certain Mentoring activities that are more effective than others (based on Requested Support field)? 
Do volunteer activities increase the quality of job obtained - like the salary level?
```

Waiting to head input from Chris, but I'll going to proceed with these as goals. We can change them up if Chris wants to focus somewhere else.

**Comment by mitchb63** [comment]
Same here. Waiting for input from Triet but proceeding for now.
