### ISSUE TITLE
Text cleaning

### ISSUE THREAD

**Issue by leaflettuce** [leaflettuce/teradata_challenge#3]
Once data types are set from #1, does any text within the data need cleaned? 
This should probably only be done on data/variables that chosen business questions will require to save time.

For example: 
- input errors such as 'lieutenant' v 'leutenent' (misspellings) 
- remove unneeded sections, '01 campaign advisor' (remove 01)
- splitting values, 'LA - March' into 'LA' and 'March'

**Comment by leaflettuce** [comment]
^^ solved above listed.. looking for more text processing needed.

**Comment by mitchb63** [comment]
Here are a few more that I plan to deal with tomorrow.  (I have no access to the actual data today)

df_contact$MailingCountry  #needs some consolidation

Most of these are probably fill in the blank type answers but there may be some factoring that can be done on a couple

df_contact$contact_history__c
df_contact$Service_Member_Status__c
df_contact$Add_I_Military_Service_Notes__c
df_contact$Salary_Expectations__c
df_contact$Education_Summary__c
df_contact$Summary_of_Qualifications__c
df_contact$Areas_of_Experience__c
df_contact$Military_Training_Courses_Attended__c
df_contact$Discharge_Disposition__c

**Comment by leaflettuce** [comment]
Sounds great to me! I'm going to spend later today examining the datasets (well, the ones expected to be needed for the four questions we're focusing on) to see if anything else like this pops up. I'll place particular emphasis on demo variables in contacts, as you mention.

Also, regarding _contacts$Salary_Expectations_ - If I recall if looked mostly empty, but you might find a quick rework of the function I used for _contacts$Desired_Salary_expectations_  to be useful for it.  I think the function was called _clean_salary_. 

I'll update tonight with any more variables I find!

**Comment by mitchb63** [comment]
So....when I add more cleaning code, do I add/commit/push the changes only or the entire code file to date including the changes?

**Comment by leaflettuce** [comment]
You said you cloned the repo onto your local, right? if so, when you git add/commit/push it will make all the changes to the entire directory.

Best method is usually to create and 'checkout' to a new branch, then git add/commit/'push origin (branch-name)'.

Once the code in the branch is good to merge with master, click the 'pull request' button within the branch page on this site. That will submit it for review/merging to master.

^^ I know... I hate git too but its soooo useful.  haha

Thanks!

**Comment by leaflettuce** [comment]
I just lightly cleaned up:

_contacts$MailingState
contacts$MailingCountry_

What I'll focus on this weekend (all in contact):
_last_rank
Highest_Level_education_complete
status
Job type
salary range
volunteer services
military branch_

Also, do we need to create 'time to hire' variable? Could we use 'Date_-turned_(color) variables to do this?

**Comment by mitchb63** [comment]
Yeah, I was considering options for “time to hire” and “time in program”. The end dates are easy. Date turned blue for hire and Dates turned grey or Black for exiting the program un-hired. Wasn’t sure what to use as the start. I couldn’t find Date turned red which would seem to indicate the start of active participation in the program. I can’t remember if I saw date turned green or not but that ignores all the intake time. I was thinking of using the account creation date as the start but not sure if that is the best choice. 

I wasn’t able to get any cleaning done today but fortunately, I should have the entire day free tomorrow and I plan to spend most of it on this project. Stay tuned for updates!

Mitch

**Comment by leaflettuce** [comment]
@mitchb63 Ii also split up and cleaned hire$hired_location into city and state columns. Unless I missed something, I'd say hire is good to go! 🙌

**Comment by mitchb63** [comment]
There was not really much to be done with these.  I converted these two to factors:
df_contact$Service_Member_Status__c
df_contact$Discharge_Disposition__c
I'll take a stab at adding that code (all two lines!) to the Github repo.

After looking them over more closely, I don't think the rest of these are going to be of much use.  Some of them are full of paragraphs of information but I don't think it's anything we'll be using.  Thoughts??

df_contact$contact_history__c
df_contact$Add_I_Military_Service_Notes__c
df_contact$Salary_Expectations__c
df_contact$Education_Summary__c
df_contact$Summary_of_Qualifications__c
df_contact$Areas_of_Experience__c
df_contact$Military_Training_Courses_Attended__c

**Comment by leaflettuce** [comment]
I agree with you.  We can always come back to them if they seem useful later on.

**Comment by leaflettuce** [comment]
I added some lines to clean up just a few more vars.

@mitchb63 @ChRizzo1 Do either of you see anything else we should touch on before diving into analysis? If not, I'm going to close this up and we can get into the fun part of looking for ways to solve these bus questions. 🕺

**Comment by mitchb63** [comment]
I think we’re good!

**Comment by ChRizzo1** [comment]
Nope.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by leaflettuce** [comment]
wooo, thanks!
