### ISSUE TITLE
Join datasets

### ISSUE THREAD

**Issue by leaflettuce** [leaflettuce/teradata_challenge#5]
Once questions are decided #2 and cleaning done #3 we should join the datasets as needed for analysis.

**Comment by mitchb63** [comment]
Based on what I’ve seen so far, I think the data we will be using is mostly in df_contact with a few fields from df_hire.

**Comment by leaflettuce** [comment]
I agree. This should cover most of the business questions we're focusing on. 

I'll try to see if cases/accounts are needed as well. I need to look more into it to see if volunteer info is already within the contacts df or if they need connecting as well.

**Comment by leaflettuce** [comment]
@mitchb63 @ChRizzo1 - Will either of you need these connected for data importing for analysis in R or Python? If not, I'm going to close this issue as Tableau/PBI can perform the data joining needed and save us the time.

**Comment by ChRizzo1** [comment]
No, I can operate from Tableau. Thanks!

**Comment by mitchb63** [comment]
I will probably want to do some things in R with contacts and hire joined but I can do that locally as needed.

**Comment by leaflettuce** [comment]
Sounds good, thanks both!
