### ISSUE TITLE
Find Variables of Interest

### ISSUE THREAD

**Issue by leaflettuce** [leaflettuce/teradata_challenge#7]
It could be beneficial to get a list of the variables that will be used to solve the business question listed at #2 

Anyone have thoughts on best route for this? We could keep a simple txt doc in the main dir listing them out, or add them to the EDA summary excel sheet maybe?

Once we have this it might be worth creating a custom dataset or two that drops all columns aside from these of interest to keep analysis less complicated.

**Comment by ChRizzo1** [comment]
I'm ok with your proposal.

**Comment by leaflettuce** [comment]
@ChRizzo1 awesome, I'll move this over into the business solutions milestone as I think it should take place once cleaning is finished up. More or less, we can use EDA to inform us where to focus analytics.. Maybe begin with a broad exploration and list variables that we think should be focused on more here?

Thanks!

**Comment by ChRizzo1** [comment]
Andy,
I'm posting my list of variables ( to help answer Bus Question #2) here but I can move it to EDA and look at each variable for issue etc.
This is broad and we can discuss :-)

Id
--
RecordTypeId
MailingState
MailingPostalCode
MailingCountry
LeadSource
CreatedDate
Gender__c
Race__c
Date_of_Service_Entry__c
Highest_Level_of_Education_Completed__c
DD214__c
Purple_Heart_Recipient__c
Military_Occupation__c
Primary_Military_Occupational_Specialty__c
IVMF_Service_Branch__c
Date_Vet_was_recommended_to_portal__c
Awards_and_Decorations_Earned__c
Client__c
Disability_Rating__c
O2O_Program_Participant__c
VCTP_Participant__c
Service_Branch__c
Service_Members_Status__c
O2O_Initial_Assessment_Date__c
Date_of_Separation__c
Client_Currently_Overseas__c
Education_Summary__c
Date_Of_Birth__c
If_Security_Clearance_Yes_What_kind__c
Disability_percentage_60_or_above__c
If_served_overseas_locations_of_service__c
Military_Spouse_Caregiver__c
Desired_Geographic_Region_of_Employment__c
Desired_State_s_of_Employment__c
Published_on_details__c
Date_of_Service_EntryNew__c
Reserves_National_Guard__c
Expected_Graduation_Date__c
Min_Salary_Expectations__c
Professional_Certification__c
Discharge_Type__c

**Comment by leaflettuce** [comment]
@ChRizzo1 Wow, this is great! My goal is to get an idea and list like this down as well today/tomorrow. I'll add anything of possible interest I see that you haven't already listed ^

**Comment by leaflettuce** [comment]
@ChRizzo1 after re-reading the context section of our demo bus question, I think theses will be particularly important as well as they are specifically mentioned in it:
```
_contact$client_type__c
contact$AVR__c_
```
a few more to add to your list above that could also be useful:
```
contact$last_rank
contact$status__c
hire$salary_range__c
hire$employement_type__c
hire$months_unemployed__c
hire$hired_but_still_looking__c
hire$industry_hired_in__c
```
